allowBuilds:
  esbuild: true
  msw: true
  puppeteer: false

blockExoticSubdeps: true
dedupePeers: true

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus*"
  - vite-plus
  - pnpm
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 2880

overrides:
  vite: "npm:@voidzero-dev/vite-plus-core@latest"
  vitest: "npm:@voidzero-dev/vite-plus-test@latest"

trustLockfile: true

configDependencies:
  "@pnpm/pacquet": 0.11.10

virtualStoreDirMaxLength: 60
